# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_auto_20180109_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='by_firt_player',
            field=models.BooleanField(editable=False),
        ),
    ]
