# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 17:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_auto_20180119_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='by_firt_player',
            new_name='by_first_player',
        ),
        migrations.AlterField(
            model_name='move',
            name='game',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='gameplay.Game'),
        ),
        migrations.AlterField(
            model_name='move',
            name='x',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='move',
            name='y',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
